name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump-type }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new branch
        if: steps.bump.outputs.bumped == 'true'
        run: |
          NEW_BRANCH="bump-version-${{ steps.bump.outputs.current-version }}"
          git checkout -b "$NEW_BRANCH"
          git add .
          git commit -m "Bump version to ${{ steps.bump.outputs.current-version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "$NEW_BRANCH"
      
      - name: Create a pull request
        if: steps.bump.outputs.bumped == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ inputs.github-token }}
          branch: "bump-version-${{ steps.bump.outputs.current-version }}"
          title: "Bump version to ${{ steps.bump.outputs.current-version }}"
          body: "This PR bumps the project version to ${{ steps.bump.outputs.current-version }}."
          base: main
      
      - name: Enable auto-merge for the pull request
        if: steps.bump.outputs.bumped == 'true'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
      
      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
